/*
 * This source file was generated by the Gradle 'init' task
 */
package server;

import server.lib.DataCollector;
import server.lib.ManagerCLI;
import server.lib.StyleCLI;
import server.lib.contexts.CtxMoves;
import server.lib.contexts.CtxScores;
import server.lib.dev.LibLog;
import server.paperwork.GameOptT;
import server.paperwork.GameResT;
import server.paperwork.TerminalBoolT;

public final class App {
    private final static CtxScores ctxScores = new CtxScores(0, 0, 0);

    public static final void main(String[] args) {

        StyleCLI.intro();
        StyleCLI.score(ctxScores);
        StyleCLI.options();

        final GameOptT userChoice = DataCollector.gameOpt();
        if (userChoice.equals(GameOptT.EXIT))
            ManagerCLI.byeIfBored();

        final GameOptT cpuChoice = ManagerCLI.cpuMove();

        final CtxMoves ctxMoves = new CtxMoves(userChoice, cpuChoice);
        final GameResT winner = ctxMoves.getWinner();

        LibLog.emptyLine();
        StyleCLI.choices(ctxMoves);
        StyleCLI.feedbackResult(winner);

        ManagerCLI.assignPoints(ctxScores, winner);
        final TerminalBoolT ch = DataCollector.playAgain();

        if (ch.equals(TerminalBoolT.NO))
            ManagerCLI.byeIfBored();
        else
            main(args);
    }
}
