/*
 * This source file was generated by the Gradle 'init' task
 */
package server;

import server.lib.StyleCLI;

public final class App {

    public static void main(String[] args) {
        StyleCLI.intro();
        StyleCLI.score();
        StyleCLI.options();

    }
}
